"""Comment-aware lexical extraction, not framework or registration resolution."""

import re

from pygments.lexers import CSharpLexer
from pygments.token import Comment, String


METHODS = "Get|Post|Put|Delete|Patch|Head|Options"
ATTRIBUTE = re.compile(r"\bHttp(" + METHODS + r")(?:Attribute)?\b")
REGISTRATION = re.compile(r"\.\s*Map(" + METHODS + r")\s*\(")


def extract_dotnet(source):
    if "<auto-generated" in source[:2000].casefold():
        return [], ["Auto-generated C# content was not promoted to features"]
    if re.search(r"(?m)^\s*#\s*if\b", source):
        return [], ["Conditional C# compilation was not resolved; the file was deferred for review"]
    masked = list(source)
    for offset, token_type, value in CSharpLexer().get_tokens_unprocessed(source):
        if token_type in Comment or token_type in String:
            for position in range(offset, offset + len(value)):
                if masked[position] not in "\r\n":
                    masked[position] = " "
    code = "".join(masked)
    hits = []
    for group in re.finditer(r"\[[^\]]*\]", code):
        for attribute in ATTRIBUTE.finditer(group.group()):
            offset = group.start() + attribute.start()
            hits.append({
                "method": attribute.group(1).upper(), "rule": "http-attribute",
                "offset": offset, "line": source.count("\n", 0, offset) + 1,
            })
    for registration in REGISTRATION.finditer(code):
        offset = registration.start()
        hits.append({
            "method": registration.group(1).upper(), "rule": "minimal-api-registration",
            "offset": offset, "line": source.count("\n", 0, offset) + 1,
        })
    return sorted(hits, key=lambda item: (item["offset"], item["method"])), []